services:
  - type: web
    name: chatapp-backend
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: singapore
    autoDeploy: true
    envVars:
      - key: PORT
        value: "8080"
      - key: DATABASE_URL
        fromDatabase:
          name: chatapp-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: chatapp-redis
          property: connectionString
      - key: REDIS_ADDR
        fromService:
          type: redis
          name: chatapp-redis
          property: connectionString

  - type: redis
    name: chatapp-redis
    plan: free
    ipAllowList: []
    region: singapore

databases:
  - name: chatapp-db
    plan: free
    databaseName: chat_db
    region: singapore
